// domain/types.ts
//
// The vocabulary of the app. These describe the data itself and mention React
// nowhere — which is what lets the rules in workflow.ts be tested on their own.

/** The three kinds of account. */
export type Role = 'Employee' | 'Manager' | 'Senior Manager'

/** The two roles that can approve. `Exclude` removes 'Employee' from Role. */
export type ApproverRole = Exclude<Role, 'Employee'>

export type User = {
  id: string
  name: string
  email: string
  role: Role
}

/** Where one approval stage has got to. */
export type StageDecision = 'pending' | 'approved' | 'rejected'

/**
 * One stage of approval. Note it names a ROLE, not a person: any user holding
 * that role can decide it (except whoever submitted the form). Who actually
 * did is recorded afterwards in `decidedBy*`.
 */
export type ApprovalStage = {
  role: ApproverRole
  decision: StageDecision
  decidedById: string | null
  decidedByName: string | null
  decidedAt: string | null
}

/**
 * The four states a form can be in, as shown to the submitter.
 *
 * This is NOT stored on the form — it's worked out from the form each time it
 * is needed (see getStatus). Storing it as well would be a second source of
 * truth that could end up disagreeing with the first.
 */
export type FormStatus = 'Draft' | 'Under review' | 'Approved' | 'Rejected'

export type FormRequest = {
  id: string
  /** The autogenerated form number, e.g. "FORM-0001". */
  number: string
  /** What the form is called, typed by the submitter. */
  name: string
  amount: number
  submitterId: string
  submitterName: string
  createdAt: string
  /** null while the form is still a draft; set when it's submitted. */
  submittedAt: string | null
  /** Empty while a draft — the stages are worked out at the moment of submission. */
  stages: ApprovalStage[]
}

/** What the "new form" screen collects. */
export type NewFormInput = {
  name: string
  amount: number
}
